### ISSUE TITLE
Stairs & Door Castle Tileset Addition

### ISSUE THREAD

**Issue by Zefk** [solarus-games/solarus-sample-quest#5]
I added some stairs based on the original stairs in the sample quest tileset. You will notice them in the upper right corner. No credit required.

![castle tiles](https://cloud.githubusercontent.com/assets/19560764/23591993/5d21cd26-01b7-11e7-972e-c9ef73581878.png)

[castle.dat.zip](https://github.com/solarus-games/solarus-sample-quest/files/819807/castle.dat.zip)

**Comment by Zefk** [comment]
I made further modifications.

**Sprites > entities > door**
![door](https://cloud.githubusercontent.com/assets/19560764/23616887/71a32038-0248-11e7-86b2-5e7404f559d1.png)

[entities.zip](https://github.com/solarus-games/solarus-sample-quest/files/821616/entities.zip)

**Castle Tileset:**

![castle tiles](https://cloud.githubusercontent.com/assets/19560764/23616994/c27b1fe2-0248-11e7-8ca5-dd586d32f98c.png)

[tilesets.zip](https://github.com/solarus-games/solarus-sample-quest/files/821624/tilesets.zip)

**Comment by christopho** [comment]
Can you make a pull request? Thanks

**Comment by Zefk** [comment]
Would you like me to send pull requests for the other CC0 (public domain) graphics? I made most of these and modified the rest for the book project, but they are public domain. I am almost done with the entity chapter.

![final_entity_section](https://cloud.githubusercontent.com/assets/19560764/23637648/1a3b820c-029a-11e7-97a4-96f1ac1c9526.png)

![dialog_box](https://cloud.githubusercontent.com/assets/19560764/23637198/8aa5e4f4-0297-11e7-8331-383e3047d447.png)

![hearts](https://cloud.githubusercontent.com/assets/19560764/23637227/b9aa57b2-0297-11e7-983e-d03f65d8f785.png)
![item_icon](https://cloud.githubusercontent.com/assets/19560764/23637228/b9ca67a0-0297-11e7-9eca-4758bad68d1f.png)
![rupee_icon](https://cloud.githubusercontent.com/assets/19560764/23637229/b9ca9ea0-0297-11e7-9bd5-243d248b9b47.png)
![abraz_key](https://cloud.githubusercontent.com/assets/19560764/23637243/d8850d08-0297-11e7-8dca-1d22e41d3a27.png)
![miscellaneous](https://cloud.githubusercontent.com/assets/19560764/23637252/ea5de68a-0297-11e7-9b94-efbfd39d593d.png)
![stream](https://cloud.githubusercontent.com/assets/19560764/23637261/f999837a-0297-11e7-8d4d-7806a54432b4.png)
![switch_2](https://cloud.githubusercontent.com/assets/19560764/23637262/f9a7dff6-0297-11e7-9aba-36d09f941910.png)
The font is CC0 and is apparently named after a spice drink.
![green_digits](https://cloud.githubusercontent.com/assets/19560764/23637310/2d26335a-0298-11e7-87e4-7a406575b3bd.png)
![white_digits](https://cloud.githubusercontent.com/assets/19560764/23637403/bcf57de2-0298-11e7-8e53-11ec4499efb9.png)
